Is 98 business dash photo upload
CPSECapstone/Isoko pull request #66
Opened 2022-03-18 22:42 UTC by shriyan44

2022-04-14 18:44 UTC, jpoist97 requested changes
Please delete the .DS_Store files you added here. Also bring back the get-user-object and put-user-object functions to whatever they look like on master so that they don't show up in the files changed on this PR

2022-04-14 18:54 UTC, jpoist97 reviewed
Looks good other than the extra files and stuff, good job!

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/package.json
> +      "@material-ui/lab": "^4.0.0-alpha.60",
Is this package used anywhere and if so why is it an alpha version?

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/src/components/imageUpload/Crop.tsx
> +   // position: center;
```suggestion
```

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/src/components/imageUpload/cropImage.js
> +      const image = new Image();
I'm not gonna review this file assuming it's just the file you copied from the package right?

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/src/components/imageUpload/multiImageUpload.tsx
> +                  <Col key={index}>
How many Images do you want in one Row at each size? I think we should specify the Col size here rather than not putting it at all

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/src/components/imageUpload/Crop.tsx
> +         // console.log(croppedImage);
```suggestion
```

2022-04-14 18:54 UTC, jpoist97 commented on frontend/isoko/src/components/imageUpload/Crop.tsx
> +   };
Just curious why did you choose to remove the UseCallback from this function?

2022-04-14 21:28 UTC, shriyan44 commented
> 

I tried to delete, not sure if it even found it but all the stackoverflows said it should be in ur gitignore and it is so it's not affecting anything

2022-04-14 22:58 UTC, jpoist97 reviewed
I get this behavior when I upload multiple photos, honestly its not the biggest deal if you don't have the sm, md, lg stuff if it's being difficult. You can revert it to how it was before and I'll approve it.

<img width="1552" alt="Screen Shot 2022-04-14 at 3 53 22 PM" src="https://user-images.githubusercontent.com/42504462/163490399-d17f5649-05d3-446a-9f1f-c1272bc184b7.png">

2022-04-15 18:27 UTC, shriyan44 commented
> I get this behavior when I upload multiple photos, honestly its not the biggest deal if you don't have the sm, md, lg stuff if it's being difficult. You can revert it to how it was before and I'll approve it.
> 
> <img alt="Screen Shot 2022-04-14 at 3 53 22 PM" width="1552" src="https://user-images.githubusercontent.com/42504462/163490399-d17f5649-05d3-446a-9f1f-c1272bc184b7.png">

Hmm it doesn't do that on mine unless i make my screen really small so that's whack I'll just remove it

2022-04-15 19:34 UTC, shriyan44 commented
> I get this behavior when I upload multiple photos, honestly its not the biggest deal if you don't have the sm, md, lg stuff if it's being difficult. You can revert it to how it was before and I'll approve it.
> 
> <img alt="Screen Shot 2022-04-14 at 3 53 22 PM" width="1552" src="https://user-images.githubusercontent.com/42504462/163490399-d17f5649-05d3-446a-9f1f-c1272bc184b7.png">

reverted changes, doesn't do that anymore

2022-04-18 17:06 UTC, jpoist97 commented
Did you push your changes? Doesn't look like there were any commits after my review and I still get the same behavior

2022-04-21 21:19 UTC, merged